/// <reference types="cypress" />
import { apiProduct, fill, submit } from '../support/data'

describe('Administração com histórico persistido — DRS atual', () => {
  before(() => { cy.task('prepararAdmin', null, { timeout: 65000 }); cy.task('prepararAdmin', null, { timeout: 65000 }) })
  it('Perfis locais — somente Lucas Paulino e Admin; demais clientes consultáveis sem login', () => {
    cy.visit('/perfis')
    cy.get('a.profile-card').should('have.length', 3) // Admin, Lucas, ação de cadastro (não é perfil).
    cy.contains('a.profile-card', 'Lucas Paulino').should('be.visible')
    cy.contains('a.profile-card', 'Administrador').should('be.visible')
    cy.contains('a.profile-card', 'Marina Oliveira').should('not.exist')
    cy.contains('a.profile-card', 'João da Couves').should('not.exist')
    cy.contains('a.profile-card', 'Administrador').click()
    cy.visit('/admin/clientes')
    cy.get('form[aria-label="Filtros de clientes"]').within(() => { fill({ email: 'marina.oliveira@techstore.test' }); submit('Consultar clientes') })
    cy.get('tbody tr').should('have.length', 1).and('contain', 'Marina Oliveira')
    cy.contains('button', 'Consultar / alterar').click()
    cy.contains('h2', 'Cliente: Marina Oliveira').should('be.visible')
    cy.contains('h3', 'Histórico de atividades').should('be.visible')
    cy.contains('Pedido ').should('exist')
  })
  it('RF0055/RF0057 RN0071/RN0073 RNF0043 — período e categorias, meses sem vendas zerados e dados históricos', () => {
    cy.visit('/admin/analises')
    cy.get('form[aria-label="Filtros de vendas"]').within(() => {
      fill({ inicio: '2025-10-01', fim: '2026-09-30' }); cy.contains('button', 'Limpar categorias').click()
      cy.contains('label', 'Memórias RAM').find('input').check()
      cy.contains('label', 'Processadores').find('input').check()
      submit('Aplicar filtros')
    })
    cy.contains('summary', 'Dados do gráfico').click()
    cy.get('table[aria-label="Dados de vendas"] thead th').should('have.length', 3)
    cy.get('table[aria-label="Dados de vendas"] tbody tr').should('have.length', 12)
    cy.get('table[aria-label="Dados de vendas"] tbody tr').first().should('contain', '10/2025').and('contain', '0,00')
    cy.get('.sales-chart canvas').should('be.visible')
    cy.document().then(doc => expect(doc.documentElement.scrollWidth).to.be.at.most(doc.documentElement.clientWidth))
    cy.screenshot('analise-vendas', { capture: 'viewport' })
  })
  it('RF0056 RN0072 — rejeita datas invertidas, intervalos inválidos e ausência de categoria', () => {
    cy.visit('/admin/analises')
    cy.get('form[aria-label="Filtros de vendas"]').within(() => { fill({ inicio: '2026-09-01', fim: '2026-08-01' }); submit('Aplicar filtros') })
    cy.contains('[role="alert"]', 'A data final não pode ser anterior à inicial.').should('be.visible')
    cy.get('form[aria-label="Filtros de vendas"]').within(() => { fill({ inicio: '2026-09-01', fim: '2026-09-02' }); submit('Aplicar filtros') })
    cy.contains('[role="alert"]', 'Selecione um intervalo de 1 a 24 meses.').should('be.visible')
    cy.get('form[aria-label="Filtros de vendas"]').within(() => { fill({ inicio: '2024-01-01', fim: '2026-09-30' }); submit('Aplicar filtros') })
    cy.contains('[role="alert"]', 'Selecione um intervalo de 1 a 24 meses.').should('be.visible')
    cy.get('form[aria-label="Filtros de vendas"]').within(() => { fill({ inicio: '2026-09-01', fim: '2026-09-30' }); cy.contains('button', 'Limpar categorias').click(); submit('Aplicar filtros') })
    cy.contains('[role="alert"]', 'Selecione ao menos uma categoria').should('be.visible')
    cy.contains('button', 'Exportar planilha (CSV)').should('be.disabled')
  })
  it('RF0058 — exporta a mesma análise em planilha CSV, com datas, categoria e valor', () => {
    cy.visit('/admin/analises')
    cy.get('form[aria-label="Filtros de vendas"]').within(() => {
      fill({ inicio: '2025-10-01', fim: '2026-09-30' }); cy.contains('button', 'Limpar categorias').click()
      cy.contains('label', 'Memórias RAM').find('input').check(); submit('Aplicar filtros')
    })
    cy.intercept('GET', '**/api/analises/vendas/exportacao?*').as('csv')
    cy.contains('button', 'Exportar planilha (CSV)').should('not.be.disabled').click()
    cy.wait('@csv').its('response.statusCode').should('eq', 200)
    cy.readFile('cypress/downloads/tech-store-vendas.csv').should('include', 'Início;Fim;Mês;Categoria;Valor (R$)').and('include', '2025-10;"Memórias RAM";0,00')
  })
  it('RF0051/RF0052 RN0050/RN0051 RN0061/RN0062 RNF0064 — registra fornecedor e entrada, recalcula preço e consulta persistência', () => {
    apiProduct().then(p => {
      const name = 'Fornecedor Cypress ' + Date.now()
      cy.visit('/admin/estoque')
      cy.contains('button', 'Cadastrar fornecedor').click()
      cy.get('form[aria-label="Cadastrar fornecedor"]').within(() => { fill({ nome: name }); submit() })
      cy.get('form[aria-label="Cadastrar fornecedor"]').should('not.exist')
      cy.contains('button', 'Registrar entrada').click()
      cy.get('form[aria-label="Registrar entrada de estoque"]').within(() => {
        cy.get('[name="produto"]').select(p.id + ' — ' + p.nome)
        cy.get('[name="fornecedor"] option').contains(name).then(option => cy.get('[name="fornecedor"]').select(option.val() as string))
        fill({ quantidade: '0', custo: '80', data: new Date().toLocaleDateString('en-CA') }); submit()
        cy.contains('[role="alert"]', 'quantidade').should('be.visible')
        fill({ quantidade: '2' }); submit()
      })
      cy.get('form[aria-label="Registrar entrada de estoque"]').should('not.exist')
      cy.get('table[aria-label="Entradas de estoque"]').should('contain', p.nome).and('contain', name)
      cy.reload()
      cy.get('table[aria-label="Entradas de estoque"]').should('contain', p.nome)
      cy.request('/api/produtos/' + p.id).then(r => { expect(r.body.quantidade).to.eq(12); expect(r.body.custo).to.eq(80); expect(r.body.preco).to.eq(108) })
    })
  })
})
