/// <reference types="cypress" />

describe('Perfil Lucas persistido para testes', () => {
  it('RF0025 RN0027 — prepara histórico idempotente e consulta pedidos, pagamentos, trocas, cupons e atividades', () => {
    cy.task('prepararPerfilLucas', null, { timeout: 65000 })
    cy.task('prepararPerfilLucas', null, { timeout: 65000 })
    cy.request('/api/clientes?email=lucas.paulino%40techstore.test').then(r => {
      expect(r.body).to.have.length(1)
      const lucas = r.body[0]
      expect(lucas.ranking).to.eq(3)
      cy.request('/api/clientes/perfis').then(perfis => {
        const perfil = perfis.body.find((p: { id: string }) => p.id === lucas.id)
        expect(perfil).to.have.all.keys('id', 'nome', 'ativo', 'selecionavel')
        expect(perfil.selecionavel).to.eq(true)
      })
      cy.request('/api/clientes/' + lucas.id + '/transacoes').then(({ body }) => {
        expect(body.pedidos).to.have.length(4)
        expect(body.pagamentos).to.have.length(5)
        expect(body.trocas).to.have.length(2)
        expect(body.cupons).to.have.length(4)
        expect(body.atividades.length).to.be.greaterThan(10)
        const delivered = body.pedidos.find((p: { couponCodes: string[] }) => p.couponCodes.includes('LUCAS-BOASVINDAS-USADO'))
        expect(delivered.payments).to.have.length(2)
        expect(delivered.numero).to.be.a('number').and.be.at.least(111082)
        expect(new Set(body.pedidos.map((p: { numero: number }) => p.numero)).size).to.eq(4)
        expect(delivered.payments.reduce((total: number, p: { amount: number }) => total + p.amount, 0)).to.eq(delivered.total - delivered.desconto)
        expect(JSON.stringify(body)).not.to.include('4111111111111111').and.not.to.include('codigoSeguranca')
        cy.visit('/perfis')
        cy.contains('a.profile-card', 'Lucas Paulino').click()
        cy.contains('h2', 'Lucas Paulino').should('be.visible')
        cy.contains('h3', 'Histórico de atividades').should('be.visible')
        cy.get('[aria-label="Histórico de atividades"] li').should('have.length.greaterThan', 10)
        cy.contains('Cupom LUCAS-TECH100').should('exist')
        cy.get('[aria-labelledby="customer-transactions-heading"]').should('contain', 'Pedido ' + delivered.numero).and('not.contain', delivered.id)
        // Impede que a rolagem suave do site capture uma posição intermediária.
        cy.document().then(doc => { doc.documentElement.style.scrollBehavior = 'auto' })
        cy.get('[aria-labelledby="customer-transactions-heading"]').scrollIntoView({ offset: { top: -170, left: 0 } })
        cy.screenshot('conta-transacoes', { capture: 'viewport' })
        cy.get('[aria-labelledby="customer-activity-heading"]').scrollIntoView({ offset: { top: -170, left: 0 } })
        cy.screenshot('conta-historico', { capture: 'viewport' })
        cy.document().then(doc => expect(doc.documentElement.scrollWidth).to.be.at.most(doc.documentElement.clientWidth))
        cy.visit('/admin')
        cy.get('.brand--admin').click()
        cy.location('pathname').should('eq', '/')
        cy.get('nav[aria-label="Navegação principal"]').contains('a', /^Conta$/).click()
        cy.location('pathname').should('eq', '/conta')
        cy.contains('h1', 'Dados pessoais').should('be.visible')
        cy.visit('/pedidos')
        cy.get('.order-card').should('have.length', 4)
        cy.get('[data-order-id="' + delivered.id + '"]').should('contain', String(delivered.numero)).and('not.contain', delivered.id).within(() => cy.contains('a', 'Ver detalhes').click())
        cy.contains('h1', 'Pedido ' + delivered.numero).should('be.visible')
        cy.contains('label', 'Cupons utilizados').find('input').should('have.value', 'LUCAS-BOASVINDAS-USADO')
        cy.contains('label', 'Pagamento').find('input').should('have.value',
          delivered.payments.map((p: { brand: string; lastDigits: string; amount: number; status: string }) =>
            `${p.brand} final ${p.lastDigits}: ${p.amount.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' })} (${p.status})`).join(' · '))
        cy.reload()
        cy.contains('h1', 'Pedido ' + delivered.numero).should('be.visible')
        cy.contains('label', 'Cupons utilizados').find('input').should('have.value', 'LUCAS-BOASVINDAS-USADO')
        cy.visit('/cupons')
        cy.contains('article', 'LUCAS-TECH100').should('contain', 'Disponível')
        cy.contains('article', 'LUCAS-BOASVINDAS-USADO').should('contain', 'Utilizado')
        cy.visit('/trocas')
        cy.contains('TROCA SOLICITADA').should('be.visible')
        cy.contains('TROCA PROCESSADA').should('be.visible')
      })
    })
  })
})
